_target_: navsim.agents.basic_agent.basic_agent.BasicAgent
_convert_: 'all'

trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: 'all'
    time_horizon: 4
    interval_length: 0.5
  
config:
  _target_: navsim.agents.basic_agent.basic_agent.BasicAgentConfig
  _convert_: 'all'